config/routes.rb
Rails.application.routes.draw do
  root 'stores#index'
  resources :stores
  get "/health", to: 'stores#health'
  get "/fashonable", to: 'stores#fashonable'
  get "/delicious", to: 'stores#delicious'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/store.rb
class Store < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)
    # binding.pry
      if @store.save
        redirect_to root_path
      else
        redirect_to :back
      end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def health
    @stores = Store.all.order(health: :desc)
  end

  def fashonable
    @stores = Store.all.order(fashonable: :desc)
  end

  def delicious
    @stores = Store.all.order(delicious: :desc)
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(
        :name,
        :detail,
        :health,
        :fashonable,
        :delicious,
        :image
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/_footer.html.haml
#contents.m-0.p-0
  .inner
    = link_to 'New Store', new_store_path

app/views/layouts/_header.html.haml
%header
  %h1#logo
    = link_to root_path do
      %img{:alt => "SAMPLE SEARCH", :src => "/template_assets/images/logo_top2.png"}/
  / スライドショー
  %aside#mainimg
    %img.slide1{:alt => "", :src => "/template_assets/images/1.jpg"}/
    %img.slide2{:alt => "", :src => "/template_assets/images/2.jpg"}/
    %img.slide3{:alt => "", :src => "/template_assets/images/3.jpg"}/
  / スライドショー下部の装飾用画像
  %img#kazari{:alt => "", :src => "/template_assets/images/123bg.png"}/
/ PC用（801px以上端末）メニュー
%nav#menubar.nav-fix-pos
  %ul.inner
    %li
      = link_to health_path do
        健康
        %span Health
      -# %ul.ddmenu
      -#   %li
      -#     %a{:href => "list.html"} 飲食店（XX件）
    %li
      = link_to fashonable_path do
        雰囲気
        %span Fashionable
    -# %ul.ddmenu
    -#   %li
    -#     %a{:href => "list.html"} 飲食店（XX件）
    %li
      = link_to delicious_path do
        美味しさ
        %span Delicious
    -# %ul.ddmenu
    -#   %li
    -#     %a{:href => "list.html"} 飲食店（XX件）
/ 小さな端末用（900px以下端末）メニュー

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title KibunMesi
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "/template_assets/css/style.css", :rel => "stylesheet"}/
    %link{:href => "/template_assets/css/slide.css", :rel => "stylesheet"}/
    %script{:src => "/template_assets/js/openclose.js"}
    %script{:src => "/template_assets/js/fixmenu.js"}
    %script{:src => "/template_assets/js/fixmenu_pagetop.js"}
    %script{:src => "/template_assets/js/ddmenu_min.js"}
    %script{:src => "/template_assets/js/Chart.js"}
  %body#top
    #container
      = render 'layouts/header'
      = yield
      = render 'layouts/footer'

app/views/stores/_form.html.haml
= form_with(model: store, local: true) do |form|
  = form.label '名前', class: "col-sm-3 control-label"
  = form.text_field :name, class: "form-control", placeholder: '', require: true
  = form.label '内容', class: "col-sm-3 control-label"
  = form.text_area :detail, class: "form-control", placeholder: '', require: true
  = form.label '健康', class: "col-sm-3 control-label"
  = form.number_field :health, class: "form-control", placeholder: '', require: true, min: 1, max: 5
  = form.label 'おしゃれ', class: "col-sm-3 control-label"
  = form.number_field :fashonable, class: "form-control", placeholder: '', require: true, min: 1, max: 5
  = form.label '美味しさ', class: "col-sm-3 control-label"
  = form.number_field :delicious, class: "form-control", placeholder: '', require: true, min: 1, max: 5
  = form.label '写真', class: "col-sm-3 control-label"
  = form.file_field :image, class: "form-control", require: true
  .actions
    = form.submit

app/views/stores/delicious.html.haml
#contents
  .inner
    %section
      %h2
        おいしい飯
        %span List of Reccomendations
      %table.table
        %thead
          %tr
            %th
            %th 名前
            %th うまいポイント
            %th けんこうポイント
            %th おしゃれポイント
            %th
          - @stores.each do |store|
            %tbody
              %tr
                %td.store-img
                  = image_tag store.image_url(:square_md), {:style => "width: 100px"} if store.image.present?
                %td= store.name
                %td= store.delicious
                %td= store.health
                %td= store.fashonable
                %td= link_to '詳細', store_path(store.id), class:'btn btn-info'

        -#
        -# - @stores.each do |store|
        -#     = link_to store_path(store.id) do
        -#       .store-box
        -#         - if store.image.present?
        -#           = image_tag store.image_url(:square_md), class: 'store-img'
        -#         = store.name
        -#         .top-condition
        -#           %p うまいポイント
        -#           = store.delicious
        -#         .second-condition
        -#           %p けんこうポイント
        -#           = store.health
        -#         .therd-condition
        -#           %p おしゃれポイント
        -#           = store.fashonable

app/views/stores/edit.html.haml
#contents
  .inner
    %h1 Editing Store
    = render 'form', store: @store
    = link_to 'Show', @store
    |
    = link_to 'Back', stores_path

app/views/stores/fashonable.html.haml
#contents
  .inner
    %section
      %h2
        おしゃれ飯
        %span List of Reccomendations
      %table.table
        %thead
          %tr
            %th
            %th 名前
            %th おしゃれポイント
            %th うまいポイント
            %th けんこうポイント
            %th
          - @stores.each do |store|
            %tbody
              %tr
                %td.store-img
                  = image_tag store.image_url(:square_md), {:style => "width: 100px"} if store.image.present?
                %td= store.name
                %td= store.fashonable
                %td= store.delicious
                %td= store.health
                %td= link_to '詳細', store_path(store.id), class:'btn btn-info'

app/views/stores/health.html.haml
#contents
  .inner
    %section
      %h2
        けんこう飯
        %span List of Reccomendations
      %ul
      %table.table
        %thead
          %tr
            %th
            %th 名前
            %th けんこうポイント
            %th おしゃれポイント
            %th うまいポイント
            %th
          - @stores.each do |store|
            %tbody
              %tr
                %td.store-img
                  = image_tag store.image_url(:square_md), {:style => "width: 100px"} if store.image.present?
                %td= store.name
                %td= store.health
                %td= store.fashonable
                %td= store.delicious
                %td= link_to '詳細', store_path(store.id), class:'btn btn-info'

app/views/stores/index.html.haml
-# %p#notice= notice
-# %h1 Stores
-# %table
-#   %thead
-#     %tr
-#       %th 名前
-#       %th 詳細
-#       %th 健康
-#       %th おしゃれ
-#       %th 美味しさ
-#   %tbody
-#     - @stores.each do |store|
-#       %tr
-#         %td= store.name
-#         %td= store.detail
-#         %td= store.health
-#         %td= store.fashonable
-#         %td= store.delicious
-#
-#         %td= link_to 'Show', store
-#         %td= link_to 'Edit', edit_store_path(store)
-#         %td= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' }
-# %br/
-# = link_to 'New Store', new_store_path





%nav#menubar-s
  %ul
    %li
      %a{:href => "index.html"}
        ホーム
        %span Home
    %li
      %a{:href => "recruit.html"}
        健康
        %span Health
    %li
      %a{:href => "info.html"}
        雰囲気
        %span Fashionable
    %li
      %a{:href => "faq.html"}
        美味しさ
        %span Delicious
#contents
  .inner
    %section
      %h2
        おすすめ飯
        %span List of Reccomendations
      %ul.list2
        - @stores.each do |store|
          %li
            = link_to store_path(store.id) do
              - if store.image.present?
                = image_tag store.image_url(:square_md), class: 'welcome-img'
              = store.name
              -# = link_to '編集', edit_store_path(store)

app/views/stores/new.html.haml
#contents
  .inner
    %h1 New Store
    = render 'form', store: @store
    = link_to 'Back', stores_path

app/views/stores/show.html.haml
#contents
  .inner
    .main
      %section
        %h2.type1= @store.name
        .list
          %span.icon.color1= @store.name
          %h2
            店舗のアピールポイント
            %span Information
          .container
            %div
              %canvas#myChart

          %h4
            %a{:href => "item.html"}= @store.name

          %table.ta1
            %tr
              %th 店舗情報
              %td= @store.name
            %tr
              %th 詳細
              %td
                %p= @store.detail
            %tr
              %th アクセス
              %td JR五反田駅から徒歩5分


%script{:language => "javascript", :type => "text/javascript"}
  var result1 = 12;
  var result2 = 13;
  var result3 = 15;

  var ctx = document.getElementById("myChart").getContext('2d');


  var myChart = new Chart(ctx, {
  type: 'pie',
  data: {
  labels: ["健康", "オシャレ", "美味しさ"],
  datasets: [{
  backgroundColor: [
  "#00FF00",
  "#0000FF",
  "#FF0000",
  ],
  data: [result1, result2, result3]
  }]
  }
  });